Use effective_message instead of message
This should eliminate source of
AttributeError: 'NoneType' object has no attribute 'reply_text'
during update.